// File generated by Antigravity AI representing default Firebase configurations for skillarena-1eb00.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configurations for project: skillarena-1eb00

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'PLACEHOLDER_WEB_API_KEY'),
    appId: '1:666192930154:web:c0d2097d1f5af9dc193113',
    messagingSenderId: '666192930154',
    projectId: 'skillarena-1eb00',
    authDomain: 'skillarena-1eb00.firebaseapp.com',
    storageBucket: 'skillarena-1eb00.firebasestorage.app',
    measurementId: 'G-KR9ERLZ9Z3',
    databaseURL: 'https://skillarena-1eb00-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'PLACEHOLDER_ANDROID_API_KEY'),
    appId: '1:666192930154:android:b70aa1cfc69ce610193113',
    messagingSenderId: '666192930154',
    projectId: 'skillarena-1eb00',
    storageBucket: 'skillarena-1eb00.firebasestorage.app',
    databaseURL: 'https://skillarena-1eb00-default-rtdb.firebaseio.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'PLACEHOLDER_IOS_API_KEY'),
    appId: '1:666192930154:ios:180f733d3b3b801e193113',
    messagingSenderId: '666192930154',
    projectId: 'skillarena-1eb00',
    storageBucket: 'skillarena-1eb00.firebasestorage.app',
    iosBundleId: 'com.example.skillarena',
    databaseURL: 'https://skillarena-1eb00-default-rtdb.firebaseio.com',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: 'PLACEHOLDER_MACOS_API_KEY'),
    appId: '1:666192930154:ios:180f733d3b3b801e193113',
    messagingSenderId: '666192930154',
    projectId: 'skillarena-1eb00',
    storageBucket: 'skillarena-1eb00.firebasestorage.app',
    iosBundleId: 'com.example.skillarena',
    databaseURL: 'https://skillarena-1eb00-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: 'PLACEHOLDER_WINDOWS_API_KEY'),
    appId: '1:666192930154:web:dd823dff1309d5bb193113',
    messagingSenderId: '666192930154',
    projectId: 'skillarena-1eb00',
    authDomain: 'skillarena-1eb00.firebaseapp.com',
    storageBucket: 'skillarena-1eb00.firebasestorage.app',
    measurementId: 'G-864VPMC4NN',
    databaseURL: 'https://skillarena-1eb00-default-rtdb.firebaseio.com',
  );
}
